# Generated by Django 3.0.7 on 2020-06-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=20)),
                ('asset_description', models.CharField(max_length=30)),
                ('asset_currency', models.CharField(max_length=10)),
                ('asset_initial_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('asset_current_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('asset_open_date', models.DateField(verbose_name='opening date')),
                ('asset_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('STOCK', 'Stock'), ('ASSET', 'Asset')], default='BANK', max_length=6)),
            ],
        ),
    ]
